apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: assesment-deployment
  labels:
    app: assesment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assesment
  template:
    metadata:
      labels:
        app: assesment
    spec:
      containers:
      - name: assesment_container
        image: assesment:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: assesment-service
  labels:
    app: assesment
spec:
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: assesment
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: assesment-ingress
spec:
   backend:
      serviceName: assesment-service
      servicePort: 80
